# nginx:
#     build: ./nginx
#     links:
#         - kestrel:kestrel
#     ports:
#         - "8080:80"
# kestrel:
#     build: .
#     ports:
#         - "80"

nginx-prod:
    image: gilesfa/webapp-nginx-prod
    container_name: nginx-prod
    links:
        - kestrel-prod:kestrel
    ports:
        - "8081:80"
kestrel-prod:
    image: gilesfa/webapp-dotnetcore-prod
    container_name: webapp-prod
    ports:
        - "80"
busybox-prod:
    image: sequenceiq/busybox
    container_name: busybox-prod
    links:
        - nginx-prod:nginx-prod
    command: /bin/bash -c 'sleep 3600'
